export BEANBEAVER_OCR_NAME=beanbeaver-receipt-ocr
export BEANBEAVER_OCR_HOST_PORT=${BEANBEAVER_OCR_HOST_PORT:-8001}
export BEANBEAVER_OCR_INTERNAL_PORT=${BEANBEAVER_OCR_INTERNAL_PORT:-8000}
set -xe
podman build --network=slirp4netns -t $BEANBEAVER_OCR_NAME .
podman run --replace --name $BEANBEAVER_OCR_NAME --network=slirp4netns -e BEANBEAVER_OCR_INTERNAL_PORT=$BEANBEAVER_OCR_INTERNAL_PORT -p $BEANBEAVER_OCR_HOST_PORT:$BEANBEAVER_OCR_INTERNAL_PORT $BEANBEAVER_OCR_NAME
